config/routes.rb
Chatty::Application.routes.draw do
  post "chats/login"
  post "chats/send_msg"
  get "chats/show"
  post "chats/logout"
  get "chats/start"

  root :to => "chats#start"
end

app/models/chat.rb
class Chat
  include Mongoid::Document
  field :name, type: String

  has_many :users, inverse_of: 'chat', class_name: 'User'
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :gender, type: Boolean
  field :ln,   type: String
  belongs_to :chat

  before_create :save_down

  def save_down
    self.ln = self.name.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def ensure_login
    if session[:user_id].nil?
      redirect_to chats_start_path
    end
  end

  def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block), :ext => {:auth_token => FAYE_TOKEN}}
    uri = URI.parse("http://nodey-server.herokuapp.com/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_filter :ensure_login, except: [:start,:login]
  def login
    name = params[:name]
    if name.blank? or name.length < 3
      render text: "blank"
      return;
    end
    if Chat.first.nil?
      Chat.create(name:"First")
    end
    @user = Chat.first.users.find_by(ln: name.downcase)
    if @user
      render text: "exists"
      return
    else
      @user = User.new
      @user.name = name
      @user.chat = Chat.first
      @user.gender = params[:gender]
      @user.save!
    end
    session[:user_id] = @user.id
    render "login.js"
  end

  def show
    @users = Chat.first.users
    @user = User.find(session[:user_id])
  end

  def logout
    @user = User.find(session[:user_id])
    Chat.first.users = Chat.first.users - [@user]
    session[:user_id] = nil
    render "logout.js"
  end

  def send_msg
    @name = params[:name]
    @content = params[:content]
  end

  def start
    if session[:user_id]
      redirect_to chats_show_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block), :ext => {:auth_token => FAYE_TOKEN}}
    uri = URI.parse("http://nodey-server.herokuapp.com/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end

  def subscribe(room)
    raw "<script type=\"text/javascript\">
          $( function(){
            var client = new Faye.Client('http://nodey-server.herokuapp.com/faye');
            client.setHeader('Access-Control-Allow-Origin', '*');
            client.connect();
            Faye.Transport.WebSocket.isUsable = function(_,c) { c(false) }
            client.subscribe(\""+room+"\", function(data) {
            eval(data);
            });
          });
      </script>"
  end

  def pre
    raw "<script type=\"text/javascript\">
        $(document).ready(function(){
          $('#new_msg').keypress(function(event){
              if(event.keyCode == 13){
                $('#send_msg').click();
              }
            });
          $(\".main\").scrollTop($(\".main\")[0].scrollHeight);
          $(\"#send_msg\").click(function(){
            var cont = $(\"#new_msg\").val();
            if(cont.length == 0)
              return false;
            var name = '#{@user.name}';
            $.ajax({
              url:'#{ chats_send_msg_path }',
              type:'POST',
              datatype:'json',
              traditional:true,
              data:{
                content: cont,
                name: name
              },
              timeout: 20000,
            });
          });
        });
      </script>"
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/login.html.erb
<h1>Chats#login</h1>
<p>Find me in app/views/chats/login.html.erb</p>

app/views/chats/login.js.erb
<% broadcast "/chat/main" do %>
  buzzOnline( "<%= @user.name %>","<%= @user.id %>");
<% end %>

app/views/chats/logout.js.erb
<% broadcast "/chat/main" do %>
  buzzOffline( "<%= @user.name %>","<%= @user.id %>");
<% end %>
window.location.href = "<%= chats_start_path %>"

app/views/chats/send_msg.js.erb
<% broadcast "/chat/main" do %>
  <% message_mob = @message %>
  appendWeb("<%= @content %>"," <%= @name %>");
  scrollDown();
<% end %>
$("#new_msg").val('');

app/views/chats/show.html.erb
<body onbeforeunload="CloseIt()">
  <div class="logo2">Chatty Appy!</div>
  <div class="slider shadow">
      <div class="slider-toggle"> Search venues</div>
      <div>
        <input type="text" value="40.7484,73.9847" class="ll"/>
        <input type="button" class="sq btn btn-success" value="Go">
        <div class="images">

        </div>
      </div>
    </div>
  <div class="chat-wrapper shadow"> 
    <table class="main-table">
      <tr>
        <td>
        </td>
        <td>
          <%= link_to "Disconnect", chats_logout_path, class: "disconnect btn btn-danger pull-right", method: :post, remote: true %>
          <br><br>
        </td>
      </tr>
      <tr>
        <td>
          <div class="chat main">

          </div>
        </td>
        <td class="users-td">
          <div class="users">
            <% @users.each do |user| %>
              <div class="user" id="<%= user.id %>">
                <%= user.name %>
              </div>
            <% end %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <input type="text" id="new_msg">
        </td>
        <td>
          <input type="button" id="send_msg" class="btn btn-primary" value="send">
        </td>
      </tr>
    </table>
    <div class="rel">
      <div class="notify shadow"> koko betengana bebe</div>
    </div>
    <%= subscribe "/chat/main" %>
    <br>
    <%= pre %>
  </div>
  <script type="text/javascript">
    var photos = new Array();
    $(".user").each(function(i){
      var r=Math.floor((Math.random()*190)+100);
      var g=Math.floor((Math.random()*190)+100);
      var b=Math.floor((Math.random()*190)+100);
      var br = r-20;
      var bg = g-20;
      var bb = b-20;
      $(this).css("background-color","rgb("+r+","+g+","+b+")");
      $(this).css("border","1px solid rgb("+br+","+bg+","+bb+")");
    });

    function getFour(option,val){
      var ids = new Array();
      url='https://api.foursquare.com/v2/venues/search?v=20120101&'+option+'='+val+'&client_id=TS0SJXF3W5QT4JYRF3QYNJRG4UG5JBJBBGKB5RIVQF3G1AIF&client_secret=A0P3KA3W4DWOJA3WAU0BWROLVZT2UGWMXHM3E3B45QT5FDEY&limit=6';
      $.getJSON(url, function(data){
        $.each(data.response.venues, function(j,ven){
          ids[j] = ven.id;
        });
        $('.images').html('');
        if(ids.length == 0)
          $(".images").append("Sorry, no venues near these cooardinates");
        var noImage = true;
        for(var i=0;i<ids.length;i++){
        $.getJSON('https://api.foursquare.com/v2/venues/'+ids[i]+'/photos?v=20100101&client_id=TS0SJXF3W5QT4JYRF3QYNJRG4UG5JBJBBGKB5RIVQF3G1AIF&client_secret=A0P3KA3W4DWOJA3WAU0BWROLVZT2UGWMXHM3E3B45QT5FDEY&limit=10',
          function(data) {
            $.each(data.response.photos.groups[1].items, function(j,venues){
              if(venues.sizes.items[1].url.length > 5){
              $('<img style="margin: 0px 0px 20px 20px;" class="photos" src="'+venues.sizes.items[1].url+'" />').hide().appendTo('.images');
            }
              $('.photos').load(function(){
                $(this).slideDown();
              });
             });
        });
      }
      });
    }
    $(document).ready( function(){
      $(".sq").click(function(){
        $('.photos').slideUp();
        var val = $(".ll").val();
        if(val.indexOf(",") > -1)
          getFour("ll",val.replace(/\s/g, ""));
        else
          getFour("near",val);
      });

    });
</script>
</body>

app/views/chats/start.html.erb
<div class="login-wrapper shadow">
  <div class="logo shake">
    Chatty Appy!
  </div>
  <div class="login">
    <input type="text" placeholder="Name" id="name-field">
    <br>
    <input type="radio" id="male" name="group1" value="1" checked> 
    Male
    <br>
    <input type="radio" id="female" name="group1" value="0"> 
    Female
    <br>
    <br>
    <div class="btn btn-primary shake" id="go"> 
        Go! 
      </div>
    <div class="errors shadow"></div>
    <div class="rel">
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
          var busy = false;
          function next(data){
            busy = false;
            if(data == "exists"){
              $(".errors").html("Name exists!");
            $(".errors").slideDown("slow").delay(5000).slideUp("slow");
            }else if(data == "blank"){
              $(".errors").html("Name can't be blank nor less than 3 characters");
            $(".errors").slideDown("slow").delay(5000).slideUp("slow");
            }else
              window.location = "<%= chats_show_path %>";
          }
          $('#name-field').keypress(function(event){
              if(event.keyCode == 13){
                $('#go').click();
              }
            });
          $("#go").click(function(){
            if(!busy){
              busy = true;
            }else
              return false;
            $(".errors").html('');
            var name = $("#name-field").val();
            var gender = 0;
            if($("#male").is(":checked"))
              gender = 1;
            var handler = '#{@handler}';
            $.ajax({
              url:"<%= chats_login_path %>",
              type:'POST',
              datatype:'json',
              traditional:true,
              data:{
                name: name,
                gender: gender
              },
              timeout: 5000,
              success:next
            });
          });
          // $(".test").delay(100).animate({rotate: '30deg'},500,'easeOutCirc').animate({rotate: '-30deg'},500,'easeOutCirc').animate({rotate: '30deg'},500,'easeOutCirc').animate({rotate: '-30deg'},500,'easeOutCirc').animate({rotate: '30deg'},500,'easeOutCirc').animate({rotate: '-30deg'},500,'easeOutCirc');
          $lo = $(".logo");
          $lo.delay(200).animate({top:"+152px"},1500,'easeOutBounce');
          //$(".test").hide();
          //$(".test").fadeIn({duration: 3000, easing: "easeInOutBounce"});
        });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatty</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "faye" %>
    <%= javascript_include_tag "bootstrap.min" %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      function CloseIt(){
      $.ajax({
              url:"<%= chats_logout_path %>",
              type:'POST',
              async: false,
              datatype:'json',
              traditional:true,
              data:{
              },
              timeout: 5000,
        });
      }
    </script>
  </head>
  <body>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
  <script type="text/javascript">
      var i;
      arr = ["#e5e5e5","#C8DCFF"];
      var n=25;
      for(i=0;i<n;i++){
        var width = parseInt($(window).width())+100;
        var height = parseInt($(window).height())+100;
        var x=Math.floor((Math.random()*width)-150);
        var y=Math.floor((Math.random()*height)-150);
        var w=Math.floor((Math.random()*400)+100);
        var h=Math.floor((Math.random()*400)+100);
        var l=-1;
        index = Math.floor(Math.random()*2);
        if(i>n/2)
          color = arr[0];
        else
          color = arr[1];
        colorb = color;
        if(color == "#e5e5e5")
          colorb = "#757575";
        var rad=Math.floor(h/2);
        $("body").append('<div class="bk" style="position:absolute;width:'+w+'px;height:'+h+'px;left:'+x+'px;top:'+y+'px;z-index:'+l+';background-color:transparent;border-radius:'+rad+'px;box-shadow: 1px 1px 20px '+colorb+';border:1px solid '+color+';"></div>');
        }
  </script>
</html>